# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Fuji"
license = "GPLv3"
licenselink = "https://github.com/amzrk2/hugo-theme-fuji/blob/master/LICENSE"
description = "A minimal Hugo theme inspired by Murasaki, powered by GitHub Primer CSS."
homepage = "https://github.com/amzrk2/hugo-theme-fuji/"
tags = ["blog", "minimal", "primer"]
features = ["responsive"]
min_version = "0.62.1"

[author]
  name = "DSRKafuU(amzrk2)"
  homepage = "https://amzrk2.cc/about/"
